name: "Check code formatting"

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  checker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Prepare
        run: |
          sudo apt install -y clang-format
      - name: Format
        run: |
          find src -iname "*.[h,c]" -exec clang-format -i {} \;
          git checkout src/arch/arm/asm.h src/arch/x86/asm.h
      - name: Check
        run: |
          git status
          git diff --quiet
